/*******************************************
* INITIAL DATABASE FILE CREATED FOR GM-SIS *
********************************************/

/* AUTHENTICATION */
CREATE TABLE AUTHENTICATION
(
  USERNAME  VARCHAR(50)    PRIMARY KEY NOT NULL,
  PASSWORD  TEXT                NOT NULL,
  SYSADM   BOOLEAN             NOT NULL
);


/* CUSTOMER TABLE */
CREATE TABLE CUSTOMER
(
  ID              INT     PRIMARY KEY   NOT NULL,
  FULLNAME        TEXT                  NOT NULL,
  ADDRESS         TEXT                  NOT NULL,
  POSTCODE        TEXT                  NOT NULL,
  EMAIL           TEXT                  NOT NULL,
  CUSTOMERTYPE    TEXT                  NOT NULL
);
/* VEHICLE TABLE */
CREATE TABLE VEHICLE
(
 REGISTRATION INT PRIMARY KEY NOT NULL,
 CUSTOMERID   INT NOT NULL,
 MAKE         TEXT  NOT NULL,
 MODEL        TEXT  NOT NULL,
 ENGINESIZE   INT   NOT NULL,
 FUELTYPE     TEXT  NOT NULL,
 COLOUR       TEXT  NOT NULL,
 MOTDATE      DATE  NOT NULL, 
 LASTSERVICE  DATE  NOT NULL,
 MILEAGE      INT   NOT NULL,
 FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE WARRANTY
(
 REGISTRATION INT NOT NULL,
 NAME       TEXT NOT NULL,
 ADDRESS    TEXT NOT NULL,
 EXPIRYDATE DATE NOT NULL,
 FOREIGN KEY(REGISTRATION) REFERENCES VEHICLE(REGISTRATION)
);
/* PARTS TABLE */
CREATE TABLE STOCKPARTS (
  ID                INT     PRIMARY KEY  NOT NULL,
  NAME              TEXT                 NOT NULL,
  DESCRIPTION       TEXT                 NOT NULL,
  COST              INT                  NOT NULL
);
CREATE TABLE REPAIRS (
  ID                INT     PRIMARY KEY  NOT NULL,
  VEHICLEID         INT                  NOT NULL,
  CUSTOMERID        INT                  NOT NULL,
  TOTALCOST         INT                  NOT NULL,
  FOREIGN KEY(VEHICLEID) REFERENCES VEHICLE(ID),
  FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE REPAIRPARTS (
  ID                INT     PRIMARY KEY     NOT NULL,
  REPAIRID          INT                     NOT NULL,
  PARTNAME          INT                     NOT NULL,
  WARRANTYEND       INT                     NOT NULL,
  WARRANTYSTART     INT                     NOT NULL,
  FOREIGN KEY(REPAIRID) REFERENCES REPAIRS(ID)
);
/* SPECIALIST REPAIRS TABLE */
CREATE TABLE SPECIALISTREPAIRS
(
CUSTOMERID   INT      NOT NULL,
CONTRACT VARCHAR(255) NOT NULL,
ITEMID VARCHAR(255)   NOT NULL,
SPCID INT             NOT NULL,
DELIVERYDATE DATE     NOT NULL,
RETURNDATE DATE       NOT NULL,
COST INT              NOT NULL,
FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE CENTRES
(
SPCID INT NOT NULL,
NAME VARCHAR(255) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
TELEPHONE VARCHAR(11) NOT NULL,
EMAIL VARCHAR(255) NOT NULL
);
/* BOOKINGS TABLE */
CREATE TABLE BOOKINGS (
	ID	INT	PRIMARY KEY NOT NULL,
	BOOKDATE	DATE NOT NULL,
	TIME	INT NOT NULL,
	TYPE	TEXT	NOT NULL,
	MILAGE INT NOT NULL,
	CUSTOMERID	INT NOT NULL,
	VEHICLEREGISTRATION  INT NOT NULL,
	EMPLOYEEID INT NOT NULL,	
	FOREIGN KEY(CUSTOMERID) references CUSTOMER(ID),
	FOREIGN KEY(VEHICLEREGISTRATION) references VEHICLE(REGISTRATION),
	FOREIGN KEY(EMPLOYEEID) references EMPLOYEE(ID)
);
